export const PLANT_TYPES = [
  { id: 'padi', name: 'Padi', harvestDays: 90, icon: '🌾' },
  { id: 'jagung', name: 'Jagung', harvestDays: 75, icon: '🌽' },
  { id: 'kedelai', name: 'Kedelai', harvestDays: 80, icon: '🫘' },
  { id: 'kacang-tanah', name: 'Kacang Tanah', harvestDays: 90, icon: '🥜' },
  { id: 'cabe', name: 'Cabe', harvestDays: 90, icon: '🌶️' },
  { id: 'tomat', name: 'Tomat', harvestDays: 75, icon: '🍅' },
  { id: 'terong', name: 'Terong', harvestDays: 80, icon: '🍆' },
  { id: 'kangkung', name: 'Kangkung', harvestDays: 30, icon: '🥬' },
  { id: 'bayam', name: 'Bayam', harvestDays: 25, icon: '🥬' },
  { id: 'sawi', name: 'Sawi', harvestDays: 40, icon: '🥬' },
  { id: 'wortel', name: 'Wortel', harvestDays: 70, icon: '🥕' },
  { id: 'bawang-merah', name: 'Bawang Merah', harvestDays: 60, icon: '🧅' },
  { id: 'bawang-putih', name: 'Bawang Putih', harvestDays: 90, icon: '🧄' },
  { id: 'kentang', name: 'Kentang', harvestDays: 90, icon: '🥔' },
  { id: 'ubi-kayu', name: 'Ubi Kayu', harvestDays: 240, icon: '🍠' },
  { id: 'ubi-jalar', name: 'Ubi Jalar', harvestDays: 120, icon: '🍠' },
  { id: 'kacang-panjang', name: 'Kacang Panjang', harvestDays: 50, icon: '🫛' },
  { id: 'labu', name: 'Labu', harvestDays: 90, icon: '🎃' },
  { id: 'mentimun', name: 'Mentimun', harvestDays: 60, icon: '🥒' },
  { id: 'semangka', name: 'Semangka', harvestDays: 80, icon: '🍉' },
  { id: 'melon', name: 'Melon', harvestDays: 75, icon: '🍈' },
  { id: 'stroberi', name: 'Stroberi', harvestDays: 90, icon: '🍓' },
  { id: 'cabai-rawit', name: 'Cabai Rawit', harvestDays: 90, icon: '🌶️' },
  { id: 'selada', name: 'Selada', harvestDays: 40, icon: '🥬' },
  { id: 'brokoli', name: 'Brokoli', harvestDays: 70, icon: '🥦' },
  { id: 'kubis', name: 'Kubis', harvestDays: 90, icon: '🥬' },
]

